version: '3.7'
services:
    go:
        image: golang
        volumes:
          - .:/src/redmine-automatization-bot
        working_dir: /src/redmine-automatization-bot
        entrypoint: 'sh init.sh'